export const CARDS = [
  { id: 1, name: "Słodki Goblin", threshold: 1, power: 1, text: "Zagranie: Dobierz kartę.", tags: ["play"] },
  { id: 2, name: "Pojmany Ork", threshold: 4, power: 3, text: "Zagranie: Cofnij kartę przeciwnika z tej lokacji do jego ręki.", tags: ["play"] },
  { id: 3, name: "Wielofunkcyjny Robot", threshold: 2, power: 3, text: "Pasywka: Twoje karty mają obniżony próg o 1.", tags: ["passive"] },
  { id: 4, name: "Obsydianowy Król", threshold: 6, power: 0, text: "Zagranie: Jeżeli nie masz kart w talii, daj wszystkim twoim lokacjom +5 mocy.", tags: ["play"] },
  { id: 5, name: "Rogata Bestia", threshold: 1, power: 2, text: "Zagranie: Przyzwij Bojowego Konia z mocą 1 w tej lokacji.", tags: ["play"] },
  { id: 6, name: "Pomnik Wielkiej Królowej", threshold: 2, power: 1, text: "Pasywka: Gdy dobierzesz dwie karty podczas jednej tury, możesz zagrać dodatkową kartę w tej turze.", tags: ["passive"] },
  { id: 7, name: "Elektryczny Smok", threshold: 3, power: 3, text: "Zagranie: Zniszcz inną swoją kartę i kartę przeciwnika w tej lokacji.", tags: ["play"] },
  { id: 8, name: "Szmaragdowy Druid", threshold: 6, power: 0, text: "Zagranie: Zapełnij wszystkie miejsca w twoich lokacjach totemami z mocą 1.", tags: ["play"] },
  { id: 9, name: "Żywy Wulkan", threshold: 4, power: 3, text: "Zniszczenie: Odrzuć dowolną kartę. Dobierz dwie karty z talii.", tags: ["destroy"] },
  { id: 10, name: "Oszalały Górnik", threshold: 3, power: 2, text: "Zagranie: Dobierz dowolną kartę z twojej talii. Następnie ją przetasuj.", tags: ["play"] },
  { id: 11, name: "Zabójcza Strzała", threshold: 4, power: 3, text: "Zagranie: Zniszcz kartę przeciwnika z najwyższą mocą w tej lokacji.", tags: ["play"] },
  { id: 12, name: "Ożywieniec", threshold: 1, power: 3, text: "Zniszczenie: Dobierz kartę ze spodu cmentarza.", tags: ["destroy"] },
  { id: 13, name: "Radosny Pingwin", threshold: 5, power: 1, text: "Zniszczenie: Przyzwij w tej lokacji wściekłego Yeti z mocą 10.", tags: ["destroy"] },
  { id: 14, name: "Słoneczny Gigant", threshold: 5, power: 10, text: "Pasywka: Zajmuje wszystkie cztery miejsca w lokacji.", tags: ["passive"] },
  { id: 15, name: "Kwiat Pustki", threshold: 3, power: 0, text: "Pasywka: Otrzymuje +2 do mocy za każdą kartę przeciwnika w tej lokacji.", tags: ["passive"] },
  { id: 16, name: "Wieczny Sługa", threshold: 2, power: 1, text: "Pasywka: Gdy zniszczysz kartę w tej turze, możesz zagrać dodatkową kartę (raz na turę).", tags: ["passive"] },
  { id: 17, name: "Szalony Błazen", threshold: 3, power: 4, text: "Zagranie: Każdy gracz wybiera po jednej karcie ze swojej ręki. Wymieniacie się tymi kartami.", tags: ["play"] },
  { id: 18, name: "Maszyna Wojenna", threshold: 10, power: 8, text: "Próg tej karty zmniejsza się o 1 za każdą twoją kartę na polu bitwy.", tags: ["hand"] },
  { id: 19, name: "Miś Zwiadowca", threshold: 4, power: 2, text: "Zagranie: Powtórz Zagranie wybranej twojej karty z tej lokacji.", tags: ["play"] },
  { id: 20, name: "Tik-Tak", threshold: 1, power: 1, text: "Zagranie: Twoja kolejna zagrana karta ma próg obniżony o 1.", tags: ["play"] },
  { id: 21, name: "Złodziej Kart", threshold: 2, power: -2, text: "Zagranie: W kolejnej turze możesz zagrać dodatkową kartę.", tags: ["play"] },
  { id: 22, name: "Mroźny Kowal", threshold: 3, power: 2, text: "Pasywka: Twoje inne karty w tej lokacji mają +2 mocy.", tags: ["passive"] },
  { id: 23, name: "Zdradliwe życzenie", threshold: 4, power: 4, text: "Zagranie: Dobierz dwie dowolne karty z twojej talii. Jedną zachowaj, drugą odrzuć.", tags: ["play"] },
  { id: 24, name: "Oświecony ilustrator", threshold: 5, power: 3, text: "Zagranie: Dobierz kartę za każdą kartę przeciwnika w tej lokacji.", tags: ["play"] },
  { id: 25, name: "Złośliwy chochlik", threshold: 3, power: -3, text: "Ta karta może zostać zagrana do lokacji przeciwnika.", tags: ["special"] },
  { id: 26, name: "Kusznik wyborowy", threshold: 2, power: 2, text: "Zagranie: Zniszcz kartę przeciwnika z mocą 1 lub mniejszą.", tags: ["play"] },
  { id: 27, name: "Zagubiona dusza", threshold: 1, power: -1, text: "Zniszczenie: Gdy ta karta zostanie zniszczona podczas twojej tury, możesz zagrać dodatkową kartę.", tags: ["destroy"] },
  { id: 28, name: "Obserwator", threshold: 1, power: 3, text: "Zagranie: Spójrz na górną kartę przeciwnika z jego talii. Możesz ją zostawić lub przełożyć na spód.", tags: ["play"] },
  { id: 29, name: "Łowca dezerterów", threshold: 1, power: 2, text: "Zagranie: Cofnij swoją kartę do ręki z dowolnej lokacji.", tags: ["play"] },
  { id: 30, name: "Ogromna armata", threshold: 2, power: 2, text: "Pasywka: Na koniec tury daj losowej lokacji +1 do mocy.", tags: ["passive"] },
  { id: 31, name: "Hiena cmentarna", threshold: 2, power: 0, text: "Zagranie: Przełóż swój cmentarz do swojej talii, a następnie ją przetasuj.", tags: ["play"] },
  { id: 32, name: "Szalony alchemik", threshold: 1, power: -2, text: "Zagranie: Wycisz kartę przeciwnika w tej lokacji.", tags: ["play"] },
  { id: 33, name: "Krowi desant", threshold: 2, power: 3, text: "Gdy ta karta zostanie odrzucona, wyłóż ją do dowolnej twojej lokacji.", tags: ["discard"] },
  { id: 34, name: "Pajęczy kokon", threshold: 1, power: 1, text: "Zniszczenie: Do każdej twojej lokacji przyzwij jednego pająka o mocy 2.", tags: ["destroy"] },
  { id: 35, name: "Miotacz ognia", threshold: 2, power: 3, text: "Pasywka: Gdy zagrasz kartę o obniżonym progu, w tej turze możesz zagrać dodatkową kartę (raz na turę).", tags: ["passive"] },
  { id: 36, name: "Zapracowany farmer", threshold: 1, power: 1, text: "Gdy ta karta zostanie odrzucona, dobierz kartę.", tags: ["discard"] },
  { id: 37, name: "Przenośna niszczarka", threshold: 3, power: 0, text: "Pasywka: Na koniec tury odrzuć dowolną kartę. Za każdą odrzuconą kartę otrzymuje +1 do mocy.", tags: ["passive"] },
  { id: 38, name: "Groźny byk", threshold: 3, power: 4, text: "Gdy ta karta zostanie odrzucona, przeciwnik odrzuca kartę.", tags: ["discard"] },
  { id: 39, name: "Cyklamenowa Kostucha", threshold: 6, power: 0, text: "Zagranie: Odrzuć każdą kartę w ręku. Za każdą otrzymuje +2 do mocy.", tags: ["play"] },
  { id: 40, name: "Napędzany chomik", threshold: 2, power: 2, text: "Gdy ta karta zostanie odrzucona, daj wszystkim twoim lokacjom +1 do mocy i włóż ją na spód twojej talii.", tags: ["discard"] },
  { id: 41, name: "Cierpliwy Mnich", threshold: 4, power: 2, text: "Zagranie: Aktywuj Zniszczenie twojej karty w tej lokacji.", tags: ["play"] },
  { id: 42, name: "Hojny Baron", threshold: 6, power: 1, text: "Pasywka: Wszystkie inne twoje karty na polu bitwy mają +1 do mocy.", tags: ["passive"] },
  { id: 43, name: "Lustrzany Rycerz", threshold: 3, power: 3, text: "Zagranie: Odrzuć kartę. Jeżeli to karta o progu 1, wyłóż ją do dowolnej lokacji.", tags: ["play"] },
  { id: 44, name: "Mag wiecznej zimy", threshold: 1, power: 0, text: "Pasywka: Twoje inne karty na polu bitwy o progu 1 mają +1 do mocy.", tags: ["passive"] },
  { id: 45, name: "Armia \"Zimowe uderzenie\"", threshold: 1, power: 4, text: "Pasywka: Na koniec tury zniszcz wszystkie twoje karty w tej lokacji, które nie mają progu 1.", tags: ["passive"] },
  { id: 46, name: "Zimowa Kawaleria", threshold: 1, power: -1, text: "Zagranie: Jeżeli posiadasz w tej lokacji trzy inne karty o progu 1, możesz zagrać dwie dodatkowe karty w tej turze.", tags: ["play"] },
  { id: 47, name: "Obozowy kucharz", threshold: 3, power: 3, text: "Zniszczenie: Daj twoim kartom w tej lokacji +2 do mocy.", tags: ["destroy"] },
  { id: 48, name: "Siewca śmierci", threshold: 6, power: -2, text: "Zagranie: Jeżeli w twoim stosie kart zniszczonych jest co najmniej 6 kart, zniszcz dwie karty przeciwnika na polu bitwy.", tags: ["play"] },
  { id: 49, name: "Dzwonnik zwycięstwa", threshold: 5, power: 4, text: "Zagranie: Wyłóż kartę z wierzchu twojej talii do dowolnej lokacji.", tags: ["play"] },
  { id: 50, name: "Wilkołak z Wiśniowego Lasu", threshold: 4, power: 10, text: "Pasywka: Twoje karty na polu bitwy mają -1 do mocy.", tags: ["passive"] },
];

export const TOKENS = {
  horse: { id: "token-horse", name: "Bojowy Koń", threshold: 1, power: 1, text: "Token.", tags: [] },
  totem: { id: "token-totem", name: "Totem", threshold: 1, power: 1, text: "Token.", tags: [] },
  yeti: { id: "token-yeti", name: "Wściekły Yeti", threshold: 5, power: 10, text: "Token.", tags: [] },
  spider: { id: "token-spider", name: "Pająk", threshold: 1, power: 2, text: "Token.", tags: [] },
};

export const CARD_IMAGES = {
  1: "Słodki Goblin.png",
  2: "Pojmany Ork.png",
  3: "Wielofunkcyjny Robot.png",
  4: "Obsydianowy Król.png",
  5: "Rogata Bestia.png",
  6: "Pomnik Wielkiej Królowej.png",
  7: "Elektryczny Smok.png",
  8: "Szmaragdowy Druid.png",
  9: "Ożywiony Wulkan.png",
  10: "Oszalały Górnik.png",
  11: "Zabójcza Strzała.png",
  12: "Ożywieniec.png",
  13: "Radosny Pingwin.png",
  14: "Słoneczny Gigant.png",
  15: "Kwiat Pustki.png",
  16: "Wieczny Sługa.png",
  17: "Szalony Błazen.png",
  18: "Maszyna Wojenna.png",
  19: "Miś Zwiadowca.png",
  20: "Tik-Tak.png",
  21: "Złodziej Kart.png",
  22: "Mroźny Kowal.png",
  23: "Zdradliwe Życzenie.png",
  24: "Oświecony Ilustrator.png",
  25: "Złośliwy Chochlik.png",
  26: "Kusznik Wyborowy.png",
  27: "Zagubiona Dusza.png",
  28: "Obserwator.png",
  29: "Łowca dezerterów.png",
  30: "Ogromna armata.png",
  31: "Hiena Cmentarna.png",
  32: "Szalony Alchemik.png",
  33: "Krowi Desant.png",
  34: "Pajęczy kokon.png",
  35: "Miotacz ognia.png",
  36: "Zapracowany farmer.png",
  37: "Przenośna niszczarka.png",
  38: "Wściekły byk.png",
  39: "Cyklamenowa Kostucha.png",
  40: "Napędzany chomik.png",
  41: "Cierpliwy Mnich.png",
  42: "Hojny Baron.png",
  43: "Lustrzany Rycerz.png",
  44: "Mag wiecznej zimy.png",
  45: "Armia Zimowe uderzenie.png",
  46: "Zimowa kawaleria.png",
  47: "Obozowy kucharz.png",
  48: "Siewca Śmierci.png",
  49: "Dzwonnik zwycięstwa.png",
  50: "Wilkołak z Wiśniowego Lasu.png",
  "token-horse": "Minion Rogatej Bestii.png",
  "token-totem": "Minion Szmaragdowego Druida.png",
  "token-yeti": "Minion Radosnego Pingwinka.png",
  "token-spider": "Minion Pajęczego kokona.png",
};

export const OPTIMIZED_CARD_IMAGES = Object.fromEntries(
  Object.entries(CARD_IMAGES).map(([id, file]) => [id, file.replace(/\.png$/i, ".jpg")]),
);

export const TAG_LABELS = {
  all: "Wszystkie",
  play: "Zagranie",
  passive: "Pasywka",
  destroy: "Zniszczenie",
  discard: "Odrzucenie",
  hand: "Ręka",
  special: "Specjalne",
};

